sudo: required
language: python
before_install:
- wget https://storage.googleapis.com/kubernetes-helm/helm-v2.4.1-linux-amd64.tar.gz
- tar -zxvf helm-v2.4.1-linux-amd64.tar.gz
- sudo mv linux-amd64/helm /usr/local/bin/helm
- sudo rm -rf linux-amd64 helm-v2.4.1-linux-amd64.tar.gz
script:
- python ci.py
