apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.agent.name }}-deployment"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        component: "{{ .Values.agent.name }}-deployment"
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.agent.name }}-deployment
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          resources:
{{ toYaml .Values.agent.resources | indent 12 }}
          env:
            - name: KUBERNETES_API
              value: "true"
            - name: KUBERNETES_API_TIMEOUT
              value: {{ .Values.agent.kubernetes_api.timeout | quote }}
            - name: KUBERNETES_API_LABELS
              value: {{ .Values.agent.kubernetes_api.kubernetes_labels | quote }}
            - name: PROMETHEUS
              value: {{ .Values.agent.prometheus.auto_detect_service_endpoints | quote }}
            - name: PROMETHEUS_TIMEOUT
              value: {{ .Values.agent.prometheus.timeout | quote }}
            - name: PROMETHEUS_DETECT_METHOD
              value: service
            - name: PROMETHEUS_KUBERNETES_LABELS
              value: {{ .Values.agent.prometheus.kubernetes_labels | quote }}
            - name: OS_AUTH_URL
              value: "http://{{ template "keystone.fullname" . }}:{{ .Values.keystone.service.port }}/v3"
            - name: OS_USERNAME
              value: {{ .Values.agent.keystone.os_username | quote }}
            - name: OS_USER_DOMAIN_NAME
              value: {{ .Values.agent.keystone.os_user_domain_name | quote }}
            - name: OS_PASSWORD
              value: {{ .Values.agent.keystone.os_password | quote }}
            - name: OS_PROJECT_NAME
              value: {{ .Values.agent.keystone.os_project_name | quote }}
            - name: OS_PROJECT_DOMAIN_NAME
              value: {{ .Values.agent.keystone.os_project_domain_name | quote }}
            - name: MONASCA_URL
              value: "http://{{ template "api.fullname" . }}:{{ .Values.api.service.port }}/v2.0"
            - name: LOG_LEVEL
              value: {{ .Values.agent.log_level | quote }}
            - name: INSECURE
              value: {{ .Values.agent.insecure | quote }}
            {{- if .Values.agent.namespace_annotations }}
            - name: KUBERNETES_NAMESPACE_ANNOTATIONS
              value: {{ .Values.agent.namespace_annotations | quote}}
            {{- end}}
            {{- if .Values.agent.kubernetes_api.storage.parameter_dimensions }}
            - name: STORAGE_PARAMETERS_DIMENSIONS
              value: {{ .Values.agent.kubernetes_api.storage.parameter_dimensions | quote}}
            {{- end}}
            - name: REPORT_PERSISTENT_STORAGE
              value: {{ .Values.agent.kubernetes_api.storage.report | quote }}
            {{- if .Values.agent.dimensions }}
            - name: DIMENSIONS
              value: {{ .Values.agent.dimensions | quote}}
            {{- end}}
