{{- if .Values.aggregation.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aggregation.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.aggregation.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.aggregation.metric_configuration | indent 2 }}
{{- end }}